---
- name: Check host
  hosts: [all]
  vars:
    services: [httpd, firewalld]
  tasks:
  - name: Install packages
    yum:
      name: "{{ services }}"
      state: latest
  - name: Start and enable services
    service:
      name: "{{ item }}"
      state: started
      enabled: true
    with_items: "{{ services }} "
  - name: Create index.html
    copy:
      dest: /var/www/html/index.html
      content: Welcome to my web server
  - name: Open firewall ports
    firewalld:
      service: http
      permanent: yes
      immediate: true
      state: enabled

